import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PaymentMethod, PaymentStatus } from '../../../generated/prisma/enums';

const PAGE_MARGIN = 48;
const SECTION_GAP = 18;
const LINE_GAP = 6;

export type PaymentReceiptPdfInput = {
  receiptNumber: string;
  centerName: string;
  studentName: string;
  teacherName: string;
  studentGroupName?: string | null;
  amount: number;
  paidAmount: number;
  rest: number;
  paymentDate: string;
  method: PaymentMethod;
  status: PaymentStatus;
  notes?: string | null;
};

@Injectable()
export class PaymentReceiptPdfService {
  async generateReceipt(input: PaymentReceiptPdfInput): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const document = new PDFDocument({
        size: 'A4',
        margin: PAGE_MARGIN,
        info: {
          Title: `Payment Receipt ${input.receiptNumber}`,
          Author: input.centerName,
          Subject: 'Academix Payment Receipt',
          Keywords: 'academix,payment,receipt',
        },
      });
      const chunks: Buffer[] = [];

      document.on('data', (chunk: Buffer | Uint8Array) => {
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
      });
      document.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
      document.on('error', (error: Error) => {
        reject(error);
      });

      this.renderHeader(document, input);
      this.renderSummary(document, input);
      this.renderFooter(document);

      document.end();
    });
  }

  private renderHeader(
    document: PDFKit.PDFDocument,
    input: PaymentReceiptPdfInput,
  ): void {
    document.font('Helvetica-Bold').fontSize(20).text(input.centerName);
    document
      .moveDown(0.3)
      .font('Helvetica-Bold')
      .fontSize(16)
      .fillColor('#111827')
      .text('Payment Receipt');

    document
      .moveDown(0.2)
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#4b5563')
      .text(`Receipt #: ${input.receiptNumber}`)
      .text(`Issued at: ${this.formatDate(input.paymentDate)}`);

    document.moveDown(0.6);
    document
      .strokeColor('#d1d5db')
      .lineWidth(1)
      .moveTo(PAGE_MARGIN, document.y)
      .lineTo(document.page.width - PAGE_MARGIN, document.y)
      .stroke();

    document.moveDown(0.8);
  }

  private renderSummary(
    document: PDFKit.PDFDocument,
    input: PaymentReceiptPdfInput,
  ): void {
    const summaryRows = [
      ['Student', input.studentName],
      ['Teacher', input.teacherName],
      ['Group', input.studentGroupName ?? 'Private payment'],
      ['Status', this.toReadableStatus(input.status)],
      ['Method', this.toReadableMethod(input.method)],
      ['Expected amount', this.formatCurrency(input.amount)],
      ['Paid amount', this.formatCurrency(input.paidAmount)],
      ['Remaining balance', this.formatCurrency(input.rest)],
    ] as const;

    document.font('Helvetica-Bold').fontSize(12).fillColor('#111827');

    for (const [label, value] of summaryRows) {
      document.text(`${label}: `, {
        continued: true,
      });
      document.font('Helvetica').text(value);
      document.font('Helvetica-Bold').moveDown(0.2);
    }

    if (input.notes && input.notes.trim().length > 0) {
      document.moveDown(SECTION_GAP / 36);
      document.font('Helvetica-Bold').text('Notes');
      document
        .moveDown(LINE_GAP / 12)
        .font('Helvetica')
        .fillColor('#374151')
        .text(input.notes.trim(), {
          width: document.page.width - PAGE_MARGIN * 2,
        });
    }
  }

  private renderFooter(document: PDFKit.PDFDocument): void {
    document.moveDown(1.5);
    document
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#6b7280')
      .text('Generated by Academix. Keep this document as proof of payment.', {
        align: 'center',
      });
  }

  private formatDate(value: string): string {
    return new Intl.DateTimeFormat('en-US', {
      year: 'numeric',
      month: 'short',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    }).format(new Date(value));
  }

  private formatCurrency(amount: number): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount);
  }

  private toReadableStatus(status: PaymentStatus): string {
    switch (status) {
      case PaymentStatus.PAID:
        return 'Paid';
      case PaymentStatus.PARTIALLY_PAID:
        return 'Partially paid';
      case PaymentStatus.UNPAID:
        return 'Unpaid';
      default:
        return status;
    }
  }

  private toReadableMethod(method: PaymentMethod): string {
    switch (method) {
      case PaymentMethod.CASH:
        return 'Cash';
      default:
        return method;
    }
  }
}
